### PR TITLE
Links as a list in readme

### PR DESCRIPTION
**Pull request by gbabin**

### CODE REVIEW

**Comment by ClutchplateDude** [comment]
I'm a little confused.... where is this file even displayed?

**Comment by andre-stefanov** [comment]
> I'm a little confused.... where is this file even displayed?

Github repository home page

**Comment by ClutchplateDude** [comment]
> > I'm a little confused.... where is this file even displayed?
> 
> Github repository home page

Well, the reason I'm confused is because I looked there (https://github.com/OpenAstroTech/OpenAstroTracker) but could not find the readme in its "before" state...

**Comment by andre-stefanov** [comment]
> > > I'm a little confused.... where is this file even displayed?
> > 
> > 
> > Github repository home page
> 
> Well, the reason I'm confused is because I looked there (https://github.com/OpenAstroTech/OpenAstroTracker) but could not find the readme in its "before" state...

The difference can be seen between:
https://github.com/OpenAstroTech/OpenAstroTracker
and
https://github.com/gbabin/OpenAstroTracker/tree/fix-readme

**Review by ClutchplateDude — APPROVED** [review]

**Pull request merged**
